import React from 'react';
import { 
  Network, 
  ShieldCheck, 
  Database, 
  Lock, 
  FileKey, 
  RefreshCw,
  Fingerprint,
  Radio
} from 'lucide-react';

export function OpalProvenanceNetworkSection() {
  const pillars = [
    {
      title: 'TRUST',
      subtitle: 'Rooted in physical reality',
      desc: 'Trust is not generated by marketing or speculative trading. It is anchored directly in miner-side XRF spectroscopy, peer consensus, and physical specimen custody.',
      icon: ShieldCheck,
    },
    {
      title: 'PERSISTENCE',
      subtitle: 'Immutable record longevity',
      desc: 'Records outlive individual mining syndicates, companies, or digital platforms. The provenance archive is mathematically sealed to endure for centuries.',
      icon: Database,
    },
    {
      title: 'TRACEABILITY',
      subtitle: 'Unbroken chain of custody',
      desc: 'From the subterranean drive at -14.2m to an art museum in Zurich, every transfer of stewardship is publicly auditable without exposing confidential miner coordinates.',
      icon: Radio,
    },
    {
      title: 'PROVENANCE',
      subtitle: 'The living story of place',
      desc: 'The technical infrastructure serves one foundational mission: ensuring that the story, human effort, and geological prehistory of every stone is never erased.',
      icon: Fingerprint,
    },
  ];

  return (
    <div id="opal-provenance-network" className="w-full flex flex-col gap-8">
      {/* Section Header */}
      <div className="flex flex-col gap-4 border-b border-[rgba(245,243,237,0.1)] pb-8">
        <div className="flex items-center gap-2">
          <Network className="w-4 h-4 text-[#C5A059]" />
          <span className="font-mono text-xs tracking-[0.25em] text-[#C5A059] uppercase">
            SECTION 05 // INFRASTRUCTURE & CONTINUITY
          </span>
        </div>

        <div className="flex flex-col lg:flex-row lg:items-end justify-between gap-6">
          <div>
            <h2 className="font-display text-3xl sm:text-4xl lg:text-5xl text-[#F5F3ED] font-light tracking-tight">
              OPAL PROVENANCE NETWORK
            </h2>
            <p className="font-serif italic text-lg sm:text-xl text-[#C5A059] mt-2">
              Technology is the mechanism. The stone and its story are the subject.
            </p>
          </div>

          <div className="flex items-center gap-2 bg-[#0c0c0c] px-3.5 py-1.5 rounded-lg border border-[rgba(245,243,237,0.1)] text-xs font-mono text-[#AAA]">
            <span className="w-2 h-2 rounded-full bg-emerald-400" />
            <span>OPN GENESIS PROTOCOL ACTIVE</span>
          </div>
        </div>

        <p className="font-sans text-sm text-[#AAA] max-w-3xl leading-relaxed mt-2">
          The Opal Provenance Network (OPN) is the decentralized recording infrastructure that binds physical specimens to digital twins and consensus records. We do not celebrate technology for its own sake—we deploy it so provenance remains unalterable.
        </p>
      </div>

      {/* 4 Pillars of OPN */}
      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6">
        {pillars.map((p) => {
          const Icon = p.icon;
          return (
            <div
              key={p.title}
              className="bg-[#0a0a0a] border border-[rgba(245,243,237,0.08)] rounded-xl p-6 flex flex-col justify-between"
            >
              <div>
                <div className="w-9 h-9 rounded-lg bg-[#C5A059]/10 text-[#C5A059] flex items-center justify-center mb-4">
                  <Icon className="w-4 h-4" />
                </div>
                <h3 className="font-display text-lg text-[#F5F3ED] font-normal mb-1">{p.title}</h3>
                <span className="font-mono text-[10px] text-[#C5A059] block mb-3 uppercase tracking-wider">
                  {p.subtitle}
                </span>
                <p className="font-sans text-xs text-[#999] leading-relaxed">
                  {p.desc}
                </p>
              </div>
            </div>
          );
        })}
      </div>
    </div>
  );
}
